{
 "title": "Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "GPU energy consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "query": "import \"interpolate\"\nfrom(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gpu\" and r[\"_field\"] == \"energy_consumption\")\n  |> truncateTimeColumn(unit: 1m)\n  |> keep(columns: [\"node\", \"_time\", \"_field\", \"_value\",  \"index\"])\n  |> group(columns: [\"_time\", \"node\", \"index\"])\n  |> map(fn: (r) => ({r with _value: r._value / 1000000.0}))\n  |> mean()\n  |> map(fn: (r) => ({ r with A_B: r.node + \"@\" + r.index }))\n  |> group(columns: [\"A_B\"])\n  |> drop(columns: [\"node\", \"index\"])"
    }
   ]
  },
  {
   "title": "GPU memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"interpolate\"\nimport \"math\"\nfrom(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gpu\" and (r._field == \"memory_used\" or r._field == \"memory_total\"))\n  |> truncateTimeColumn(unit: 1m)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"_time\", \"node\", \"index\"])\n  |> map(fn: (r) => ({ r with percentage: (r.memory_used / r.memory_total) * 100.0}))\n  |> map(fn: (r) => ({ \n    r with tooltip: string(v: math.round(x:r.memory_used / 1000000.0)) + \"MB / \" + string(v: math.round(x:r.memory_total / 1000000000.0)) + \"GB\"\n    }))\n  |> map(fn: (r) => ({ r with gpu: r.node + \"@\" + r.index }))\n  |> keep(columns: [\"_time\", \"gpu\", \"percentage\", \"tooltip\"])  \n  |> group(columns: [\"gpu\"])\n"
    }
   ]
  },
  {
   "title": "Work distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ollama\")\n  |> group(columns: [\"node\"])\n  |> count()\n  |> rename(columns: {_value: \" \"})\n  |> drop(columns: [\"_start\",\"_stop\",\"_time\"])"
    }
   ]
  },
  {
   "title": "Requests per Worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"ollama\"\n      and r._field == \"worker_success_message\"\n      and r.status == \"success\"\n    )\n  |> group(columns: [\"node\"])\n  |> aggregateWindow(every: 1m, fn: count)\n  |> rename(columns: {_value: \" \"})\n  |> drop(columns: [\"_start\",\"_stop\"])\n"
    }
   ]
  },
  {
   "title": "Success model requests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ollama\" and r.status == \"success\" and r._field == \"worker_success_message\")\n  |> group(columns: [\"model\"])\n  |> count(column: \"_value\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "Error distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"ollama\"\n      and r._field == \"worker_success_message\"\n      and r.code != \"200\"\n    )\n  |> group(columns: [\"node\"])\n  |> count()\n  |> rename(columns: {_value: \" \"})\n  |> drop(columns: [\"_start\",\"_stop\",\"_time\"])\n"
    }
   ]
  },
  {
   "title": "Requests per Model",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"ollama\"\n      and r._field == \"worker_success_message\"\n      and r.status == \"success\"\n    )\n  |> group(columns: [\"model\"])\n  |> aggregateWindow(every: 1m, fn: count)\n  |> rename(columns: {_value: \" \"})\n  |> drop(columns: [\"_start\",\"_stop\"])\n"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ollama\"\n    and r.status == \"success\"\n    and r._field == \"worker_success_message\")\n  |> group(columns: [\"model\"])\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\n  |> rename(columns: {_value: \"requests_per_minute\"})\n  |> max(column: \"requests_per_minute\")\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"])\n"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"HiveCore\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ollama\")\n  |> filter(fn: (r) => r[\"_field\"] == \"worker_success_message\")\n  |> filter(fn: (r) => r[\"code\"] == \"500\")\n  |> sort()"
    }
   ]
  }
 ]
}